# 17 예외처리

## 예외

프로그램이 처리되는 동안 특정한 문제가 일어났을 때

진행 중인 투린을 중단하고, 콜스택을 거슬러 올라가 예외를 전하파하는 메커니즘

예외를 처리할 수 있는 핸들러를 찾아,

함수 호출 역순으로 거슬러 올라가

예외를 처리할 수 있는 핸들러를 찾아내면 그 곳에 처리를 맡긴다.

예외를 처리하는 핸들러를 찾을 수 없다면,

그 즉시 파이썬 프로그램이 비정상 종료되며,

그 예외 내역에 대한 StackTrace(프로그램 실행 중 오류)를 출력한다.

```py
print('line1')
try:
    value = int('a') + 1
except ValueError as e:
    print(e)
print('line2')
```

## 호출한 함수 내에서 발생한 예외도 잡을 수 있따.

```py
def fn1(x, y):
    return x + y

def fn2(a, b):
    return 10 * fn1(a, b)

try:
    print(fn2('a', 10))
except TypeError as a:
    print(e)
```

## 흔히 만나는 빌드인 예외

Exception: 최상위 예외 클래스

StopIteration

* Iterator 내에서 더 이상 생산할 Item이 없을 때

* for in 구분에서 이 예외를 통해 반복문 중단을 처리

AttributeError: attirbute 참조 실패  혹은 설정이 실패한 경우

ImportError: 지정 모듈/패키지를 import 하지 못한 경우

### NotImplemenetedError

아직 구현하지 않은 부분임을 명시

```py
class Person:
    def run(self):
        raise NotImplementedError

class Doctor(Person):
    pass

class Developer(Person):
    def run(self):
        print('runrunrun')

Doctor().run()
Developer().run()
```

Doctor().run() 은 NotImplenetedError를 발생시킨다.

자식 클래스에게 run 함수 구현(Overriding)을 강제하는 효과

## 예외처리

tuple로 예외를 다수 지정할 수 있다.

as를 통해 예외 인스턴스를 획득 가능하다.

else: 예외가 발생하지 않았을 때 호출되는 블럭

finally: 예외 발생 유무에 상관없이 호출되는 블럭

## 사용자 예외 정의

```py
def fn(i):
    if i > 100:
        raise ValueError('Too Big Number: {}'.format(i))
    elif i < -100:
        raise ValueError('Too Small Number: {}'.format(i))
    return 1 * 10

try:
    fn(210)
except ValueError as e:
    print(e)
```

위, 아래 코드 모두 결과는 동일하다.

아래 코드가 좀 더 파이썬스럽고 의미전달이 명확하다.

```py
class TooBigNumberException(ValueError):
    def __init__(self, value):
        self.value = value
    
    def __str__(self):
        return 'too big number {}'.format(self.value)

class TooSmallNumberException(ValueError):
    def __init__(self, value):
        self.value = value
    
    def __str__(self):
        return 'too small number {}'.format(self.value)

def fn(i):
    if i > 100:
        raise TooBigNumberException(i)
    elif i < -100:
        raise TooSmallNumberException(i)
    return i * 10

try:
    fn(200)
except TooSmallNumberException as e:
    print(e)
except TooBigNumberException as e:
    print(e)
```